name: message.yml
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      type:
        required: false
        type: string

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook Message
        env:
          DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1396143329846104215/fy-D5I-EUYZ1NL4x4xR42hC1KFSDN_VrCT4S_G_w10IfJLHTlScC8sCWEyBa8Ly6euyZ"
          TITLE: ${{ inputs.title }}
          DESC: ${{ inputs.description }}
          TYPE: ${{ inputs.type || 'success' }}
        run: |
          
          if [ "$TYPE" = "success" ]; then
            COLOR=3066993 # 초록
          elif [ "$TYPE" = "failure" ]; then
            COLOR=15158332 # 빨강
          elif [ "$TYPE" = "warning" ]; then
            COLOR=16776960 # 노랑
          else
            COLOR=9807270 # 회색
          fi
          
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @- <<EOF 
          {
              "embeds": [
                {
                  "title": "$TITLE",
                  "description": "$DESC",
                  "color": $COLOR,
                  "fields": [
                    {
                      "name": "시간",
                      "value": "'"$(date +'%Y-%m-%d %H:%M:%S')"'"
                    }
                  ],
                  "footer": {
                    "text": "Gitbub CI/CD"
                  },
                  "timestamp": "'"$(date --iso-8601=seconds)"'"
                }
              ]
            }
          EOF